FROM node:18.18.0-bookworm

RUN apt-get update && apt-get install -y festival festvox-kallpc16k

WORKDIR /src/upworker

ADD Prebuild.mk package.js package.json package-lock.json .

RUN make -f Prebuild.mk INSTALL_DEPS_GLOBAL

RUN ln -s /usr/local/lib/node_modules/ ../node_modules

# RUN usermod -aG audio,pulse,pulse-access root

CMD ["make", "RUN"]
